# -*- coding: utf-8 -*-
"""
aplica_vereditos_lote04.py — vereditos do Lote 4 (C16-C21).
Casamento por substring; multi=True aplica a todas as ocorrencias
pendentes DENTRO DO MESMO ARQUIVO. Ordem importa (especificas antes de
genericas).
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REG = os.path.normpath(os.path.join(HERE, '..', 'registro'))

D2 = "âncora D2 (derivations/02_setor_tensorial_mT2.md)"
D6 = "âncora D6 (derivations/06_mu_alpha_quase_estatico.md)"
D8 = "âncora D8 (derivations/08_mS0_dinamica_F.md)"
D1 = "âncora D1 (derivations/01_setor_escalar_K_Omega.md)"

V = [
 # ================= C16 (28) =================
 ("C16", r"$(\beta_0,\beta_1,\beta_2,0,\beta_4)$", "Cap.14 §14.7", "CONFERE (reprise da família F1)", False),
 ("C16", r"ds_g^2 = -dt^2 + a^2(t)(\delta_{ij} + h_{ij})dx^i dx^j,", "—", "CONFERE (perturbação TT padrão do setor g; N_g=1 implícito)", False),
 ("C16", r"ds_f^2 = -\xi^2 dt^2 + b^2(t)(\delta_{ij} + \ell_{ij})dx^i dx^j,", "Cap.14 §14.2 (ξ=N_f/N_g)", "CONFERE (perturbação TT do setor f, consistente com a definição de ξ com lapses do Cap.14)", False),
 ("C16", r"\partial_i h_{ij}=0,\quad h_{ii}=0,", "—", "CONFERE (condição TT padrão)", False),
 ("C16", r"\partial_i \ell_{ij}=0,\quad \ell_{ii}=0.", "—", "CONFERE (condição TT padrão)", False),
 ("C16", r"M_f^2 r^2(\dot \ell^2 - \frac{k^2}{a^2}\ell^2) - m_{\rm mix}^2(h-\ell)^2",
  f"{D2} §3.1",
  "ERRO DE CÁLCULO — âncora D2 §3.1: o cinético do setor f está errado (usa M_f²r²·a³; a forma correta é K_ℓℓ=M_f²b³/(4ξ) — falta o fator 1/ξ e a potência de r é r³, não r²) e falta a velocidade de propagação do setor f no termo de gradiente (c_f²=ξ²/r²≠1; a fórmula usa k²/a² igual ao do setor g); forma correta completa em D2 §3.1", False),
 ("C16", r"m_{\rm mix}^2 = m^2 M_{\rm eff}^2 F(\phi) \left(\beta_1 r + 2\beta_2 r^2\right).",
  f"{D2} §3.3",
  "ERRO DE CÁLCULO — âncora D2 §3.3: a forma real é m_mix²=(m²M_eff²F/2)r[β1+β2(ξ+r)] (β3=0 para F1), que depende de ξ; mesmo no caso especial ξ=r a fórmula do texto erra por um fator 2 (D2 dá metade do valor em caixa)", False),
 ("C16", r"\beta_1 + 2\beta_2 r.$", "C16.07 acima", "ERRO DE FORMULAÇÃO (herda o erro de C16.07 — âncora D2: o fator estrutural real do setor tensorial é β1+β2(ξ+r), que só coincide com β1+2β2r se ξ=r)", False),
 ("C16", r"h_0 \propto M_g h + M_f r \ell,", "Cap.11 (mesma fórmula, lote 3); âncora D2 §4",
  "CONFERE SOB HIPÓTESE (mesma ressalva já registrada em Cap.11/lote 3: diagonalização aproximada, não exata — âncora D2 §4 mostra que os cinéticos diferem entre setores e os gradientes não são simultaneamente diagonalizáveis com a massa; a combinação exatamente massless da matriz de massa ∝(h-ℓ)² é h+ℓ não-ponderada, independente de M_g,M_f,r — a forma ponderada aqui vale só como aproximação)", False),
 ("C16", r"h_m \propto h - \ell.", f"matriz de massa ∝(h-ℓ)² — {D2} §3.2",
  "CONFERE (a direção h-ℓ é exatamente a que carrega o termo de massa, dado M_hh=M_ℓℓ=-M_hℓ da âncora D2 §3.2; ressalva de normalização canônica como em C16.09)", False),
 ("C16", r"\dot h_0^2 - \frac{k^2}{a^2}h_0^2 + \dot h_m^2 - \frac{k^2}{a^2}h_m^2 - m_T^2 h_m^2",
  f"{D2} §4",
  "ERRO DE FORMULAÇÃO — a própria âncora D2 §4 declara que \"a diagonalização do Cap.16 §16.3 é aproximada, não exata\": os cinéticos de h e ℓ diferem e dependem do tempo (M_g²a³ vs M_f²b³/ξ), e os gradientes não são simultaneamente diagonalizáveis com a massa (c_g²=1≠c_f²=ξ²/r²); a ação em caixa apresenta os dois modos com cinético/gradiente canônicos idênticos como se fosse exata — usar a base ponderada do Anexo D §D.4 e declarar a condição de adiabaticidade", False),
 ("C16", r"m_T^2 = m^2 F(\phi) \frac{M_{\rm eff}^2}{M_g^2} \left(\beta_1 r + 2\beta_2 r^2\right).",
  f"{D2} §3.3",
  "ERRO DE CÁLCULO — âncora D2 §3.3: o prefator de escala correto é M_eff²(1/M_g²+ξ/(M_f²r³)) (soma sobre os dois setores), não M_eff²/M_g² isolado; forma real completa: m_T²=m²F·M_eff²(1/M_g²+ξ/(M_f²r³))·r[β1+β2(ξ+r)] (β3=0)", False),
 ("C16", r"m_T^2 \propto r(\beta_1 + 2\beta_2 r).", "C16.12 acima",
  "ERRO (herdado de C16.12 — âncora D2: forma real depende de ξ; só coincide com r(β1+2β2r) se ξ=r, e mesmo assim falta o prefator correto)", False),
 ("C16", r"m_T^2 \ge 2 H^2. }", "—",
  "CONFERE (importada — bound de Higuchi padrão em fundo quase-de Sitter; usar com o m_T²(ξ) real da âncora D2, não com a forma refutada de C16.12/13)", False),
 ("C16", r"m_T^2 < 2H^2,", "C16.14",
  "CONFERE (consequência padrão do bound de Higuchi — helicity-0 fantasma se violado)", False),
 ("C16", r"m^2 F(\phi) r(\beta_1 + 2\beta_2 r) \ge 2H^2. }", "C16.13, C16.14",
  "ERRO (herdado — substitui a forma de m_T² já refutada em C16.13 no bound de Higuchi; usando o m_T²(ξ) real da âncora D2, o benchmark testado em D2 dá m_T²<0, ou seja Higuchi VIOLADO, não uma desigualdade a satisfazer por tuning)", False),
 ("C16", r"m_S^2 \propto m^2 F(\phi)(\beta_1 + 2\beta_2 r).", "Cap.15 (âncora D1)",
  "ERRO (reprise idêntica da fórmula de m_S² já refutada no Cap.15 — âncora D1: nenhuma massa do espectro real segue essa proporcionalidade)", False),
 ("C16", r"m_T^2 \propto r\, m^2 F(\phi)(\beta_1 + 2\beta_2 r).", "C16.13, C16.17",
  "ERRO (combina os dois erros anteriores — C16.13 e C16.17; âncoras D1 e D2)", False),
 ("C16", r"m_T^2 \sim r\, m_S^2. }", f"C16.17, C16.18; {D1}, {D2}",
  "ERRO DE FORMULAÇÃO — ambos os lados da proporcionalidade foram refutados (m_S² pela âncora D1, m_T² pela âncora D2); a relação \"estruturalmente forte\" anunciada não tem fundamento; per derivations/00_indice.md: \"remover (ambos os lados da relação caíram)\"", False),
 ("C16", r"m_T \ll k/a", "—",
  "CONFERE (condição qualitativa razoável para o modo massivo não alterar a propagação observável, independente do valor exato de m_T)", False),
 ("C16", r"m_T \lesssim H_0", "C16.20",
  "CONFERE SOB HIPÓTESE (condição razoável para escala cosmológica atual; quantitativamente depende da forma real de m_T² — âncora D2)", False),
 ("C16", r"m_T^2 \ge 2H_{\rm inf}^2.", "C16.14 (Higuchi no passado)",
  "CONFERE (mesmo bound de Higuchi aplicado no regime inflacionário passado)", False),
 ("C16", r"m_T^2(a) = m^2 F(\phi(a)) r(a)(\beta_1 + 2\beta_2 r(a)).", "C16.12",
  "ERRO (herda C16.12/13 — âncora D2: falta a dependência em ξ(a))", False),
 ("C16", r"\beta_1 + 2\beta_2 r > 0.", "Cap.15 (âncora D1)",
  "ERRO (reprise da condição no-ghost já refutada no Cap.15 — âncora D1: não decide o no-ghost; o par com cinética negativa está presente nos dois lados da raiz no ramo dinâmico)", False),
 ("C16", r"m^2 F(\phi)(\beta_1 + 2\beta_2 r) \gg H^2.", "C16.17 (âncora D1)",
  "ERRO (herda a fórmula de m_S² refutada — âncora D1)", False),
 ("C16", r"m^2 F(\phi) r(\beta_1 + 2\beta_2 r) \ge 2H^2.", "C16.16",
  "ERRO (repete C16.16 — âncora D2: forma real de m_T² depende de ξ e é negativa no benchmark testado)", False),
 ("C16", r"m_T^2 \lesssim H_0^2.", "—",
  "CONFERE SOB HIPÓTESE (condição qualitativa razoável para recuperação de GR hoje; quantitativamente depende da forma real de m_T² — âncora D2)", False),
 ("C16", r"> \beta_1 + 2\beta_2 r", f"C16.08, C16.13, C16.24; {D1}, {D2}",
  "ERRO DE FORMULAÇÃO — a conclusão central do capítulo (\"o fator estrutural único\") não se sustenta: no tensor o fator real é β1+β2(ξ+r) (âncora D2), e no escalar a saúde não é decidida por β1+2β2r (âncora D1); ARTEFATO DE CONVERSÃO adicional: o \">\" preso dentro do \"$\" é resíduo de blockquote Markdown, não conteúdo matemático", False),

 # ================= C17 (24) =================
 ("C17", r"(\beta_0,\beta_1,\beta_2,0,\beta_4), \quad V \to F(\phi)V,", "Cap.14 §14.7, §3.8", "CONFERE (reprise)", False),
 ("C17", r"\Lambda_3 \sim (m^2 M_{\rm Pl})^{1/3}.", "—",
  "CONFERE (importada da literatura — escala de forte acoplamento padrão de gravidade massiva/dRGT)", False),
 ("C17", r"\Lambda_{\rm TDCP} \sim (m^2 M_{\rm eff})^{1/3}.", "C17.02",
  "CONFERE SOB HIPÓTESE (substituição M_Pl→M_eff por analogia, declarada como tal; a extensão de Λ3 do caso de métrica única para o bimétrico com dois setores de massa distinta não é derivada, apenas postulada)", False),
 ("C17", r"H \ll \Lambda_{\rm TDCP}. }", "—", "CONFERE (condição padrão de validade EFT)", False),
 ("C17", r"H \ll (m^2 M_{\rm eff})^{1/3}.", "C17.03, C17.04", "CONFERE (substituição direta)", True),
 ("C17", r"H^3 \ll m^2 M_{\rm eff}.", "C17.05", "CONFERE (cubo de ambos os lados, válido para quantidades positivas)", False),
 ("C17", r"m_T^2 \sim m^2 F(\phi) r(\beta_1+2\beta_2 r).", "Cap.16 (âncora D2)",
  "ERRO (reprise da forma de m_T² já refutada no Cap.16 — âncora D2: depende de ξ; no benchmark testado em D2, m_T²<0, o que invalida a cadeia de inversão que segue em §17.3)", False),
 ("C17", r"m_T^2 \ge 2H^2.", "Cap.16 §16.5", "CONFERE (importada — mesma nota: usar m_T²(ξ) real)", False),
 ("C17", r"m^2 \gtrsim \frac{2H^2}{F(\phi) r(\beta_1+2\beta_2 r)}.", "C17.07, C17.08",
  "ERRO (herdado de C17.07 — âncora D2; a inversão fica sem sentido físico se m_T² real for negativo, como no benchmark de D2)", False),
 ("C17", r"\Lambda_{\rm TDCP} \sim \left( \frac{2H^2}{F r(\beta_1+2\beta_2 r)} M_{\rm eff} \right)^{1/3}.", "C17.09, C17.03",
  "ERRO (herdado de C17.09)", False),
 ("C17", r"H \ll \left( \frac{2H^2 M_{\rm eff}} {F r(\beta_1+2\beta_2 r)} \right)^{1/3}.", "C17.10, C17.04",
  "ERRO (herdado)", False),
 ("C17", r"H^3 \ll \frac{2H^2 M_{\rm eff}} {F r(\beta_1+2\beta_2 r)}.", "C17.11",
  "ERRO (herdado; álgebra do cubo em si correta, mas herda fórmula errada)", False),
 ("C17", r"H \ll \frac{2 M_{\rm eff}} {F r(\beta_1+2\beta_2 r)}.", "C17.12",
  "ERRO (herdado de C17.07 — âncora D2; a CONCLUSÃO QUALITATIVA de que Higuchi não força a teoria para fora do regime EFT provavelmente sobrevive à correção, pois M_eff≫H permanece válido mesmo com o fator β1+β2(ξ+r) correto — mas a fórmula em caixa precisa ser refeita com D2)", False),
 ("C17", r"S_m = S_m[g,\psi]", "Cap.14 §14.1 (ação completa)",
  "CONFERE (reprise do acoplamento mínimo já estabelecido)", False),
 ("C17", r"\text{Sem BD ghost abaixo de } \Lambda_{\rm TDCP}.", "C17.14",
  "CONFERE (importada da literatura — resultado padrão de Hassan-Rosen: ausência de ghost de Boulware-Deser garantida pela estrutura do potencial e acoplamento mínimo a um único setor); NOTA: a ressalva sobre β_n(φ) preservar a estrutura simétrica do potencial é qualitativa, não verificada explicitamente", False),
 ("C17", r"\delta \beta_n \sim \frac{\Lambda_{\rm cut}^4}{16\pi^2 M_{\rm eff}^2 m^2}.", "—",
  "CONFERE SOB HIPÓTESE (estimativa dimensional padrão de EFT — contagem de potências ingênua, coeficientes O(1) assumidos)", False),
 ("C17", r"\delta \beta_n \ll \beta_n.", "C17.16", "CONFERE (definição padrão de naturalidade técnica)", False),
 ("C17", r"\Lambda_{\rm cut}\sim \Lambda_{\rm TDCP}.", "C17.03",
  "CONFERE SOB HIPÓTESE (hipótese declarada — usa a Λ_TDCP original de C17.03, que não depende dos β_n, logo não herda o erro de §17.3)", False),
 ("C17", r"\delta \beta_n \sim \frac{(m^2 M_{\rm eff})^{4/3}} {16\pi^2 M_{\rm eff}^2 m^2} = \frac{m^{2/3}} {16\pi^2 M_{\rm eff}^{2/3}}.", "C17.16, C17.18",
  "CONFERE (álgebra verificada: (m²M_eff)^{4/3}/(M_eff²m²) = m^{2/3}/M_eff^{2/3} ✓)", False),
 ("C17", r"\delta \beta_n \ll 1", "C17.19",
  "CONFERE (consequência numérica correta de C17.19 para m≪M_eff, regime cosmológico)", False),
 ("C17", r"\beta_1\beta_2<0, \quad \beta_0-\frac{3\beta_1^2}{4\beta_2}>0.", "Cap.14 §14.16",
  "CONFERE (reprise confirmada — Cap.14/lote 3)", False),
 ("C17", r"\beta_1+2\beta_2 r > 0, \quad m_S^2 \gg H^2.", "Cap.15/16 (âncora D1)",
  "ERRO (reprise da condição no-ghost já refutada — âncora D1)", False),
 ("C17", r"m_T^2 \ge 2H^2, \quad m_T^2 \lesssim H_0^2 \text{ hoje}.", "Cap.16 §16.5/§16.8",
  "CONFERE SOB HIPÓTESE (bounds corretos em si — importado/qualitativo — mas aplicados à forma de m_T² refutada ao longo do capítulo; usar m_T²(ξ) real — âncora D2)", False),
 # C17.24 é substring idêntica a C17.05 ("H \ll (m^2 M_{\rm eff})^{1/3}.") -> já coberta pelo multi=True acima.

 # ================= C18 (48) =================
 ("C18", r"ds^2=-(1+2\Psi)dt^2+a^2(1-2\Phi)\delta_{ij}dx^i dx^j.", "—",
  "CONFERE (gauge de Newton padrão, importado; Ψ=potencial temporal, Φ=potencial espacial — ver nota em C21.02 sobre troca de papéis entre capítulos)", False),
 ("C18", r"\Phi=\Psi, \quad -k^2\Phi = 4\pi G a^2\rho_m\,\delta.", "C18.01",
  "CONFERE (importada — GR/ΛCDM padrão, sem anisotropic stress)", False),
 ("C18", r"-k^2\Psi = 4\pi G a^2\,\mu(k,a)\,\rho_m\,\delta,", "C18.02",
  "CONFERE (definição padrão da literatura de gravidade modificada — parametrização μ)", False),
 ("C18", r"-k^2(\Phi+\Psi)=8\pi G a^2\,\Sigma(k,a)\,\rho_m\,\delta,", "C18.01",
  "CONFERE (definição padrão — parametrização Σ)", False),
 ("C18", r"\eta_{\rm slip}(k,a)\equiv \frac{\Phi}{\Psi}.", "C18.01",
  "CONFERE (definição padrão)", False),
 ("C18", r"\mu=\Sigma=1,\quad \eta_{\rm slip}=1.", "C18.02-05",
  "CONFERE (consistência trivial: GR recuperado quando μ=Σ=η_slip=1)", False),
 ("C18", r"\ddot\delta + 2H\dot\delta -4\pi G\,\mu(k,a)\rho_m\,\delta =0.", "C18.03",
  "CONFERE SOB HIPÓTESE (forma padrão QS da equação de crescimento, dado μ; consistente com o passo QS já confirmado no Cap.6.2/lote 2)", False),
 ("C18", r"\delta'' + \left(2+\frac{H'}{H}\right)\delta' -\frac{3}{2}\Omega_m(a)\mu(k,a)\delta=0",
  "C18.07/C18.08",
  "CONFERE (forma padrão QS da equação de crescimento em variável ln a; consistente com o Cap.6.2/lote 2 e com a transformação 4πGρm=(3/2)ΩmH²; usa μ(k,a) que é refutado quando instanciado pela forma explícita — âncora D6)", True),
 ("C18", r"\mu(k,a)=1+\frac{\alpha(a)\,k^2/a^2}{k^2/a^2+m_S^2(a)}",
  D6,
  "ERRO — âncora D6: μ real é racional de grau 7/7 em k² (multi-polo, ~7 polos, incluindo pares complexos/positivos no ramo instável), não a forma Yukawa de 1 polo em caixa; α_∞≡μ(k→∞)-1=0 exatamente (não α(a) genérico); os desvios reais vivem em escalas intermediárias, não em k→∞",
  True),
 ("C18", r"m_S^2(a)\propto m^2F(\phi)\left(\beta_1+2\beta_2 r(a)\right)", "Cap.15 (âncora D1)",
  "ERRO (reprise da fórmula de m_S² já refutada — âncora D1; ver Cap.15)", False),
 ("C18", r"m_T^2(a)\propto r(a)\,m^2F(\phi)\left(\beta_1+2\beta_2 r(a)\right).", "Cap.16 (âncora D2)",
  "ERRO (reprise da fórmula de m_T² já refutada — âncora D2; ver C16.13/23)", False),
 ("C18", r"\alpha(a)\sim \frac{\epsilon^2(a)}{1+\epsilon^2(a)}",
  D6,
  "ERRO — âncora D6: α_∞≡μ(k→∞)-1=0 exatamente nos dois benchmarks testados; não existe uma função α(a) independente com essa forma — a \"força extra\" é totalmente blindada em pequena escala",
  True),
 ("C18", r"\alpha(a)=\alpha_0\,\frac{r^2(a)}{1+r^2(a)}", "C18.12",
  "ERRO (herdado de C18.12 — âncora D6: α_∞=0)", False),
 ("C18", r"\mu(k,a)\to 1\quad\text{para}\quad k/a \gg H_0", "—",
  "CONFERE SOB HIPÓTESE (requisito padrão de recuperação de GR local; mas âncora D6 mostra que ele é satisfeito AUTOMATICAMENTE pela teoria real, α_∞=0, sem exigir m_S grande nem α pequeno como as seções 18.5(i)/(ii) seguintes assumem — mesmo achado do Cap.14 §14.6/lote 3)", False),
 ("C18", r"\mu\simeq 1$", "C18.14",
  "ERRO (mecanismo desnecessário — âncora D6: μ→1 em k→∞ é automático, independente de m_S ser grande ou de α ser pequeno; além disso m_S² aqui é a forma já refutada — âncora D1 — e a \"degenerescência\" entre os dois mecanismos (i)/(ii) descrita no texto não existe na teoria real)", True),
 ("C18", r"\mu \to 1+\alpha(a).", D6,
  "ERRO — âncora D6: em k→∞ (pequenas escalas) μ→1 exatamente (α_∞=0); é o oposto qualitativo do que a fórmula afirma; os desvios reais vivem em escalas intermediárias", True),
 ("C18", r"\frac{3}{2}\Omega_m(a)\mu \to \frac{3}{2}\Omega_m(a)(1+\alpha).", "C18.17",
  "ERRO (herdado de C18.17 — âncora D6)", False),
 ("C18", r"|\alpha(a_0)| \lesssim 0.1", D6,
  "ERRO DE FORMULAÇÃO (herdado — âncora D6: não existe α(a) único bem definido; a estrutura real é multi-polo)", False),
 ("C18", r"\eta_{\rm slip}(k,a)\neq 1.", D6,
  "CONFERE (qualitativa; confirmada mesmo pela forma real multi-polo — âncora D6: η_slip é não-monotônico e ≠1 em geral)", False),
 ("C18", r"\eta_{\rm slip}(k,a)=\frac{1+\beta(a)\,k^2/(a^2(m_S^2+k^2/a^2))}{1+\alpha(a)\,k^2/(a^2(m_S^2+k^2/a^2))}",
  D6,
  "ERRO — âncora D6: η_slip real não se ajusta a uma função suave única de 1 polo; é multi-escala e não-monotônico (ex.: benchmark A: η_slip≈−0.006 em k≲1, 0.62 em k=10, →1 em k grande)", False),
 ("C18", r"\Sigma(k,a)\approx \frac{\mu}{2}(1+\eta_{\rm slip}^{-1})", "C18.03-05 (mesmo capítulo)",
  "ERRO DE CÁLCULO — a partir das definições do próprio capítulo (C18.03: -k²Ψ=4πGa²μρδ; C18.04: -k²(Φ+Ψ)=8πGa²Σρδ; C18.05: η_slip≡Φ/Ψ), a álgebra dá Σ=(μ/2)(1+η_slip), NÃO (μ/2)(1+η_slip⁻¹) como escrito (verificado por substituição: em η_slip=2, a fórmula correta dá Σ=1.5μ, a do texto dá 0.75μ); correção: trocar η_slip⁻¹ por η_slip — erro repetido em C18.45 e C19.18", False),
 ("C18", r"m_S(a)=m_{S0}\,a^{-p}", D6,
  "ERRO (herdado — parametrização construída sobre m_S(a) e α(a) já refutados como funções físicas — âncora D6; ver C18.10/12)", True),
 ("C18", r"k_\star(a)\sim a\,m_S(a).", f"{D6}, {D8}",
  "ERRO (herdado — âncora D6: a estrutura real tem ~7 polos, não um único \"joelho\"; ver também âncora D8 para o Cap.19)", False),
 ("C18", r"m_{S0}\sim H_0 e \alpha_0\sim 0.05--0.1.", D8,
  "ERRO (âncora D8: m_S0 é escolha de design observacional, não consequência dinâmica; ver também D6 para a estrutura de α refutada)", False),
 ("C18", r"k_\star(a)=a\,m_S(a)=m_{S0}\,a^{1-p}.", f"{D6}, {D8}",
  "ERRO (repete a definição de C18.26 — âncora D6/D8)", False),
 ("C18", r"\mu(k,a)\simeq 1+\alpha(a)\frac{k^2/a^2}{m_S^2(a)} \approx 1", "C18.09",
  "ERRO (herdado de C18.09 — âncora D6; regime k→0 também foge do domínio de confiança da resposta estática — ver D6 §5)", False),
 ("C18", r"\mu \to 1 \quad (GR).", "C18.31",
  "ERRO (herdado de C18.09 — âncora D6)", False),
 ("C18", r"\mu(k,a)\simeq 1+\alpha(a).", "C18.09",
  "ERRO (herdado de C18.09 — âncora D6: o oposto é verdadeiro, μ→1 exatamente em k→∞)", True),
 ("C18", r"\alpha_0 \sim 0.05\text{--}0.10, \qquad m_{S0}\sim H_0, \qquad p\gtrsim 1, \qquad q\gtrsim 0.",
  f"{D6}, {D8}",
  "ERRO (herdado — âncora D6/D8: α0 e m_S0 não são parâmetros físicos independentes na forma assumida)", False),
 ("C18", r"f(a)\equiv \frac{d\ln \delta}{d\ln a}.", "—",
  "CONFERE (definição padrão, importada — taxa de crescimento)", False),
 ("C18", r"\frac{\Delta f}{f}\sim \mathcal{O}(\alpha(a))", D6,
  "ERRO (herdado — âncora D6: α(a) não existe como função física independente)", False),
 ("C18", r"\mu\simeq 1+\alpha(a).", "C18.33",
  "ERRO (repete C18.33 — âncora D6: μ→1 exatamente em k→∞, não 1+α(a))", False),
 ("C18", r"\Phi \neq \Psi.", D6,
  "CONFERE (qualitativa, consistente com a estrutura real — âncora D6)", False),
 ("C18", r"\eta_{\rm slip}(k,a)=\frac{\Phi}{\Psi}.", "C18.05",
  "CONFERE (reprise da definição, com \\equiv substituído por = — mesmo conteúdo)", False),
 ("C18", r"\eta_{\rm slip}(k,a)= 1+\frac{\beta(a)", "C18.21/42",
  "ERRO (repete a forma de 1 polo de C18.21 — âncora D6: η_slip real é multi-escala e não-monotônico, não uma função suave de 1 polo)", False),
 ("C18", r"\beta(a)=\nu\,\alpha(a), \qquad \nu=\mathcal{O}(1).", D6,
  "ERRO (herdado — âncora D6: β(a) construída sobre α(a) refutado, e nunca derivada independentemente, apenas postulada como proporcional a α)", False),
 ("C18", r"-k^2(\Phi+\Psi)=8\pi G a^2\Sigma(k,a)\rho_m\delta", "C18.04",
  "CONFERE (reprise da definição de Σ, C18.04)", False),
 ("C18", r"\Sigma(k,a)=\frac{\mu(k,a)}{2}\left(1+\eta_{\rm slip}^{-1}(k,a)\right).", "C18.22",
  "ERRO DE CÁLCULO (repete o erro de C18.22: dado η_slip≡Φ/Ψ de C18.05/41, a álgebra correta dá Σ=(μ/2)(1+η_slip), não (μ/2)(1+η_slip⁻¹) — ver C18.22)", False),
 ("C18", r"m_S^2(a)\propto m^2F(\phi(a))(\beta_1+2\beta_2 r(a)).", "C18.10",
  "ERRO (repete C18.10 — âncora D1)", False),
 ("C18", r"m_{S0} = H_0,\quad p=1,\quad \alpha_0=0.07,\quad q=0,\quad \nu=1.", f"{D6}, {D8}",
  "ERRO (herdado — âncora D6/D8: os parâmetros não correspondem a graus de liberdade físicos na forma assumida; ver também C19 benchmarks B1/B2, mesma família de erro)", False),

 # ================= C19 (19) =================
 ("C19", r"\frac{H_0}{c}=\frac{100\,h\ {\rm km/s/Mpc}}{299792\ {\rm km/s}} \simeq 3.335\times 10^{-4}\,h\ {\rm Mpc}^{-1}.", "—",
  "CONFERE (conta numérica verificada: 100/299792≈3.336×10⁻⁴ ✓)", False),
 ("C19", r"k_{H0}\equiv \frac{H_0}{c}\approx 3.3\times 10^{-4}\,h\,{\rm Mpc}^{-1}.", "C19.01",
  "CONFERE (reprise, arredondamento razoável)", False),
 ("C19", r"k_\star(a)=a\,m_S(a)=m_{S0}a^{1-p}.", f"C18.30; {D6}, {D8}",
  "CONFERE (reprise da definição de C18.30); NOTA: k_star(a) herda o status de \"design, não dinâmica\" da âncora D8, e o \"joelho único\" que ela posiciona não existe na estrutura multi-polo real — âncora D6", False),
 ("C19", r"k_\star(a_0)=k_{H0}\approx 3.3\times 10^{-4}\,h\,{\rm Mpc}^{-1}.", "C19.03",
  "CONFERE (substituição correta, dada a definição, para m_S0=H0)", False),
 ("C19", r"k \gg k_\star \quad \Rightarrow \quad \mu(k,a)\simeq 1+\alpha(a)", D6,
  "ERRO (herdado — âncora D6: a forma μ≃1+α(a) para k grande é refutada; μ→1 exatamente em k→∞)", False),
 ("C19", r"k_\star(a_0)\sim 0.01\text{--}0.1\,h\,{\rm Mpc}^{-1}.", "—",
  "CONFERE (declaração de meta observacional, não é uma dedução)", False),
 ("C19", r"m_{S0}\sim (30\text{--}300)\,H_0.", D8,
  "NÃO-DERIVÁVEL — âncora D8: é design observacional (inversão da posição desejada do \"joelho\" dentro da janela de LSS), não consequência da dinâmica de F(φ) e do fundo; a aritmética em si confere (0.01/3.3e-4≈30, 0.1/3.3e-4≈300), mas ver também âncora D6: o \"joelho único\" que essa faixa posiciona não existe na estrutura real multi-polo", False),
 ("C19", r"m_{S0}=30H_0,\quad p=1,\quad \alpha_0=0.07,\quad q=0,\quad \nu=1.", D8,
  "NÃO-DERIVÁVEL (âncora D8: benchmark de projeto B1, não dinâmica; construído sobre m_S/α refutados como funções físicas — âncora D6)", False),
 ("C19", r"k_\star(a_0)\approx 0.01\,h\,{\rm Mpc}^{-1}.", "C19.08",
  "CONFERE (consequência aritmética correta, dada a definição: 30×3.3×10⁻⁴≈0.01 ✓ — mas ver nota em C19.07/D8 sobre o status do \"joelho\")", False),
 ("C19", r"m_{S0}=300H_0,\quad p=1,\quad \alpha_0=0.05,\quad q=0,\quad \nu=1.", D8,
  "NÃO-DERIVÁVEL (benchmark de projeto B2 — mesma nota de C19.08/D8)", False),
 ("C19", r"k_\star(a_0)\approx 0.1\,h\,{\rm Mpc}^{-1}.", "C19.10",
  "CONFERE (consequência aritmética correta: 300×3.3×10⁻⁴≈0.1 ✓ — mesma nota de C19.09)", False),
 ("C19", r"\delta'' + \left(2+\frac{H'}{H}\right)\delta' -\frac{3}{2}\Omega_m(a)\mu(k,a)\delta=0.", "C18.08",
  "CONFERE SOB HIPÓTESE (forma correta — reprise de C18.08; usa μ refutado quando instanciado — âncora D6)", False),
 ("C19", r"\mu(k,a)=1+\frac{\alpha(a)\,k^2/a^2}{k^2/a^2+m_S^2(a)}.", "C18.09",
  "ERRO (repete C18.09 — âncora D6)", False),
 ("C19", r"k_\star(a)=m_{S0}a^{1-p}.", "C19.03/C18.30",
  "CONFERE (reprise da definição — mesma nota D8)", False),
 ("C19", r"p>1 \quad \text{e}\quad q\ge 0.", f"{D6}, {D8}",
  "ERRO (herdado — âncora D6/D8: a lógica de \"ligar tarde\" via p,q pressupõe o joelho único de 1 polo, que não existe na estrutura real)", False),
 ("C19", r"-k^2(\Phi+\Psi)=8\pi G a^2\Sigma(k,a)\rho_m\delta.", "C18.04/44",
  "CONFERE (reprise da definição)", False),
 ("C19", r"\eta_{\rm slip}=\frac{\Phi}{\Psi}, \qquad -k^2\Psi=4\pi G a^2\mu\rho_m\delta.", "C18.05/03",
  "CONFERE (reprise das definições)", False),
 ("C19", r"\Sigma(k,a)=\frac{\mu(k,a)}{2}\left(1+\eta_{\rm slip}^{-1}(k,a)\right).", "C18.22/45",
  "ERRO DE CÁLCULO (repete o erro de C18.22/45: dado η_slip≡Φ/Ψ, Σ=(μ/2)(1+η_slip), não (μ/2)(1+η_slip⁻¹) — verificado por substituição em η_slip=2: fórmula correta dá Σ=1.5μ, a do corpus dá 0.75μ)", False),
 ("C19", r"\eta_{\rm slip}(k,a)=1+\frac{\beta(a)\,k^2/a^2}{k^2/a^2+m_S^2(a)}, \qquad \beta(a)=\nu\alpha(a).", "C18.21/42/43",
  "ERRO (repete a forma de 1 polo de C18.21/42 e a relação β=να de C18.43 — âncora D6)", False),

 # ================= C20 (34) — território novo, sem âncora prévia =================
 ("C20", r"\text{A TDCP-F1 possui mecanismo de screening tipo Vainshtein consistente.}", "—",
  "CONFERE (qualitativa — declaração do objetivo do capítulo, não ainda um resultado; reafirmada como conclusão em C20.34; a cadeia de estimativas que a sustenta foi verificada nesta auditoria — ver notas em C20.19-31)", False),
 ("C20", r"\mathcal{L} = \frac{M_g^2}{2}R[g] + \frac{M_f^2}{2}R[f] + m^2 F(\phi)\,\mathcal{V}_{HR}(g,f) + \mathcal{L}_\phi + \mathcal{L}_{m}[g],",
  "Cap.3/Cap.14 (ação HR completa)",
  "CONFERE (reprise da ação HR completa com F(φ) modulando o potencial e matéria acoplada só a g — consistente com Cap.3/Cap.14)", False),
 ("C20", r"F(\phi)=1+\xi\frac{\phi}{M_{Pl}}.", "—",
  "ERRO DE FORMULAÇÃO — sobrecarga grave de símbolo: ξ é a variável estrutural central ξ=N_f/N_g, definida rigorosamente no Cap.14 §14.2 e usada em todas as âncoras D1,D2,D5,D6,D8; aqui é reaproveitada, sem aviso, como constante de acoplamento adimensional em F(φ)=1+ξφ/M_Pl — colisão de notação; renomear (ex.: ξ_φ ou λ) para não confundir com o ξ estrutural", False),
 ("C20", r"m_{\rm eff}^2 = m^2 F(\phi).", "C20.03",
  "INCOMPLETA — m_eff² é introduzida sem ligação explícita com m_S²/m_T² já definidos e depois refutados nos capítulos anteriores (âncoras D1/D2); não fica claro se é uma nova quantidade ad hoc para a análise EFT de desacoplamento ou se deveria coincidir com alguma das massas físicas reais", True),
 ("C20", r"g_{\mu\nu}=\eta_{\mu\nu}+\frac{1}{M_g}h_{\mu\nu}, \qquad f_{\mu\nu}=\eta_{\mu\nu}+\frac{1}{M_f}\ell_{\mu\nu}.", "—",
  "CONFERE (expansão perturbativa padrão em torno de Minkowski para análise de limite de desacoplamento — importada da literatura dRGT/HR)", False),
 ("C20", r"\Phi^a=x^a-\frac{1}{\Lambda_3^3}\partial^a\pi.", "—",
  "CONFERE (truque de Stückelberg padrão para extração do helicity-0 — importado da literatura de gravidade massiva)", False),
 ("C20", r"\Lambda_3^3 \sim m^2 F(\phi) M_{\rm eff}", "C20.04; Cap.17 §17.1 (C17.03)",
  "CONFERE SOB HIPÓTESE (consistente com C20.04 e a escala padrão Λ³∼m²M_eff de C17.03, assumindo que m_eff² joga o papel do \"m²\" na fórmula-padrão dRGT; herda a pendência de C20.04 sobre a identidade física de m_eff)", False),
 ("C20", r"\Lambda_3^3 \approx m^2 F_0 M_{Pl}.", "C20.07",
  "INCOMPLETA — troca não anunciada de M_eff (C20.07) por M_Pl aqui; o Cap.17 (§17.1) tratou essa substituição como significativa o bastante para declará-la explicitamente (\"substituímos M_Pl→M_eff\"), mas aqui a troca inversa passa sem nota", True),
 ("C20", r"\mathcal{L}_\pi = -\frac{1}{2}Z(\phi)(\partial\pi)^2 + \frac{c_3(\phi)}{\Lambda_3^3}(\partial\pi)^2\square\pi + \frac{\alpha_V}{M_{Pl}}\pi T.",
  "—",
  "CONFERE SOB HIPÓTESE — forma padrão do galileon cúbico de teorias dRGT/HR-like no limite de desacoplamento (importada); mas os coeficientes Z(φ),c3(φ),α_V não são derivados a partir do potencial HR específico V=Σβn·en(K) da TDCP-F1 — postulados por analogia, sem o cálculo explícito de Stückelberg que os ligaria aos β_n reais", False),
 ("C20", r"Z\square\pi + \frac{2c_3}{\Lambda_3^3} \Big[(\square\pi)^2-(\partial_\mu\partial_\nu\pi)^2\Big] = -\frac{\alpha_V}{M_{Pl}}T.",
  "C20.09",
  "CONFERE (importada — EOM padrão do galileon cúbico, consequência de Euler-Lagrange de C20.09; estrutura bem conhecida na literatura de Galileons/massive gravity)", False),
 ("C20", r"\rho = M\delta^{(3)}(\vec x).", "—", "CONFERE (fonte pontual padrão)", False),
 ("C20", r"y(r)=\frac{\pi'(r)}{r}.", "—",
  "CONFERE (variável auxiliar padrão da literatura de screening Vainshtein para soluções esfericamente simétricas)", False),
 ("C20", r"Z y + \frac{4c_3}{\Lambda_3^3}y^2 = \frac{\alpha_V}{4\pi} \frac{M}{M_{Pl}} \frac{1}{r^3}",
  "C20.10",
  "CONFERE SOB HIPÓTESE (forma padrão da integração esférica de Gauss da EOM C20.10 em teorias Galileon; estrutura consistente com a literatura de Vainshtein)", False),
 ("C20", r"y \sim \frac{\alpha_V}{4\pi Z} \frac{M}{M_{Pl}} \frac{1}{r^3}", "C20.13",
  "CONFERE (limite linear correto de C20.13, desprezando o termo em y² quando y é pequeno)", False),
 ("C20", r"y^2 \sim \frac{\alpha_V}{4\pi} \frac{\Lambda_3^3}{4c_3} \frac{M}{M_{Pl}} \frac{1}{r^3}.", "C20.13",
  "CONFERE (álgebra verificada: de 4c3/Λ3³·y²=αV/(4π)·M/(Mplr³) segue y²=αVΛ3³/(16πc3)·M/(Mplr³), que é exatamente αV/(4π)·Λ3³/(4c3)·M/(Mplr³) ✓)", False),
 ("C20", r"Z y \sim \frac{4c_3}{\Lambda_3^3}y^2.", "C20.14, C20.15",
  "CONFERE (definição padrão do raio de Vainshtein — igualdade dos termos linear e quadrático)", False),
 ("C20", r"r_V \sim \left( \frac{\alpha_V c_3}{Z^2} \frac{M}{M_{Pl}} \frac{1}{\Lambda_3^3} \right)^{1/3}",
  "C20.16",
  "CONFERE SOB HIPÓTESE (estimativa de ordem de grandeza — uso de ~ consistente ao longo da seção; fatores numéricos O(4π) omitidos são esperados nesse tipo de estimativa Vainshtein, prática padrão da literatura; sondagem numérica desta auditoria confirma a ordem de grandeza resultante em C20.23/24)", False),
 ("C20", r"\Lambda_3^3 \sim m^2 F_0 M_{Pl},", "C20.08", "CONFERE (reprise)", False),
 ("C20", r"r_V \sim \left( \frac{GM}{m^2 F_0} \right)^{1/3} \times \left(\frac{\alpha_V c_3}{Z^2}\right)^{1/3}",
  "C20.17, C20.18",
  "CONFERE SOB HIPÓTESE (álgebra consistente com C20.17/18 assumindo a convenção G=1/M_Pl² em unidades naturais; NOTA: essa convenção nunca foi declarada explicitamente em nenhum capítulo anterior do corpus — INCOMPLETA)", False),
 ("C20", r"r_V \propto (GM/m_{\rm eff}^2)^{1/3}", "C20.19; C20.04",
  "CONFERE (forma padrão do raio de Vainshtein em gravidade massiva generalizada com massa efetiva; usa a definição de m_eff² de C20.04)", False),
 ("C20", r"r_S = 2GM_\odot/c^2 \approx 3\times10^3\,m.", "—",
  "CONFERE (valor padrão verificado numericamente nesta auditoria: 2GM_sol/c²≈2954 m≈3×10³m ✓)", False),
 ("C20", r"m = (1--100)H_0/c.", "—",
  "CONFERE (escolha paramétrica razoável, consistente com a ordem de grandeza discutida no Cap.19 — m_S0~H0 a 300H0)", False),
 ("C20", r"r_V^\odot \approx 5\,{\rm pc}.", "C20.19/20; r_S (C20.21)",
  "CONFERE (verificado numericamente nesta auditoria: para m=100H0, r_V≈5.6 pc, consistente com \"≈5 pc\")", False),
 ("C20", r"r_V^\odot \approx 120\,{\rm pc}.", "C20.19/20; r_S (C20.21)",
  "CONFERE (verificado numericamente nesta auditoria: para m=H0, r_V≈120.6 pc, consistente com \"≈120 pc\")", False),
 ("C20", r"1\,AU \approx 5\times10^{-6}\,pc,", "—",
  "CONFERE (conversão numérica verificada: 1AU/1pc≈4.85×10⁻⁶≈5×10⁻⁶ ✓)", False),
 ("C20", r"r_V^\odot \gg 1\,AU.", "C20.23, C20.24, C20.25",
  "CONFERE (consequência imediata verificada: r_V~5.6-120.6 pc ≫ 1AU~4.85×10⁻⁶pc, por ~6-7 ordens de grandeza)", False),
 ("C20", r"\frac{F_\pi}{F_N} \sim \alpha_V^2 \left(\frac{r}{r_V}\right)^{3/2}", "C20.09/13",
  "CONFERE (importada — expoente 3/2 é o resultado padrão de screening Vainshtein para galileon cúbico, consistente com a literatura)", False),
 ("C20", r"\left(\frac{r}{r_V}\right)^{3/2} \sim 10^{-10}--10^{-14}.", "C20.23, C20.24, C20.25",
  "ERRO DE CÁLCULO — verificado numericamente nesta auditoria: usando r_V∈[5.6,120.6]pc (C20.23/24, corretos) e r=1AU, (r/r_V)^{3/2} varia de ≈8×10⁻¹⁰ (caso pesado, r_V=5.6pc) a ≈8×10⁻¹² (caso leve, r_V=120.6pc) — ou seja ≈10⁻¹⁰–10⁻¹², não 10⁻¹⁰–10⁻¹⁴; o limite inferior está errado por ~2 ordens de grandeza; não compromete a conclusão qualitativa (supressão extrema) nem o critério PPN seguinte, que usa só o limite superior", False),
 ("C20", r"\frac{F_\pi}{F_N}(1AU) < 10^{-5}.", "C20.27",
  "CONFERE (critério padrão PPN-like, importado)", False),
 ("C20", r"r_V \gtrsim 0.01\,pc.", "C20.27, C20.29",
  "CONFERE (verificado numericamente nesta auditoria: com α_V~1, F_π/F_N(1AU)<10⁻⁵ ⟹ r_V≳0.0104 pc, arredondando para \"0.01 pc\" ✓; NOTA: a hipótese α_V~1 não é declarada explicitamente aqui)", False),
 ("C20", r"r_V^\odot \sim 5--120\,pc.", "C20.23, C20.24, C20.30",
  "CONFERE (\"margem gigantesca\" verificada numericamente: r_V^⊙ excede o limiar de 0.01pc por um fator ~500-900×)", False),
 ("C20", r"m_{\rm eff}^2 = m^2 F(\phi),", "C20.04", "CONFERE (reprise)", False),
 ("C20", r"\text{Não surge quinta força adicional relevante via }\phi\text{ no regime solar.}",
  "C20.04; verificação formal adiada ao Cap.21 §21.7",
  "INCOMPLETA — o próprio texto declara que \"a verificação formal será feita no Cap.21\"; a alegação usa \"massa efetiva grande\" sem distinguir claramente m_eff (do modo helicity-0/gráviton, C20.04) de uma eventual massa própria de φ (m_φ, só introduzida no Cap.21 §21.7, C21.24) — risco de conflação de dois papéis de massa distintos; a verificação no Cap.21 acaba sendo apenas uma condição suficiente qualitativa, não uma prova", False),
 ("C20", r"\text{A teoria sobrevive ao teste solar fundamental.}", "C20.01, C20.19-31",
  "CONFERE SOB HIPÓTESE — numericamente sustentada pela cadeia de estimativas verificada nesta auditoria (screening Vainshtein funciona e domina o bound PPN por 2-3 ordens de grandeza mesmo após a correção de C20.28), mas depende de: (i) Z(φ),c3(φ),α_V postulados por analogia dRGT, não derivados do potencial HR β_n real da TDCP-F1 (C20.09); (ii) o argumento \"sem quinta força via φ\" fica formalmente incompleto, adiado ao Cap.21 §21.7 (ver C20.33)", False),

 # ================= C21 (31) — território novo, sem âncora prévia =================
 ("C21", r"\gamma_{\rm PPN}(r)=\frac{\Psi(r)}{\Phi(r)}\,,\qquad \beta_{\rm PPN}.", "—",
  "CONFERE (definição padrão do parâmetro PPN γ, importada da literatura); ver nota em C21.02 sobre a troca de papéis Φ↔Ψ frente ao Cap.18/19", False),
 ("C21", r"ds_g^2 = -(1+2\Phi(r))\,dt^2 + (1-2\Psi(r))\,(dr^2 + r^2 d\Omega^2),", "Cap.18 §18.1 (C18.01)",
  "ERRO DE FORMULAÇÃO — sobrecarga: papéis de Φ e Ψ trocados em relação ao Cap.18 §18.1 (C18.01), onde Ψ é o potencial temporal e Φ o espacial; aqui é o oposto (Φ=temporal, Ψ=espacial) — mesmos símbolos, convenção invertida entre capítulos do mesmo corpus; renomear ou declarar explicitamente a troca (a convenção do Cap.21, isoladamente, é a PPN padrão γ=espacial/temporal — o problema é só a inconsistência entre capítulos)", False),
 ("C21", r"com |\Phi|,|\Psi|\ll 1.", "C21.02", "CONFERE (condição pós-Newtoniana padrão de campo fraco)", False),
 ("C21", r"\mathcal{L}_{\pi T} \simeq \frac{\alpha_V}{M_{\rm Pl}}\pi\,T.", "Cap.20 §20.4 (C20.09)",
  "CONFERE (reprise consistente do termo de acoplamento linear de C20.09)", False),
 ("C21", r"m_{\rm eff}^2 = m^2 F(\phi),\qquad \Lambda_3^3 \sim m^2F(\phi)\,M_{\rm eff}.", "C20.04, C20.07",
  "CONFERE (reprise)", False),
 ("C21", r"\frac{d\Phi}{dr} = \frac{GM}{r^2}\big[1+Q(r)\big], \qquad \frac{d\Psi}{dr} = \frac{GM}{r^2}\big[1+\tilde Q(r)\big].",
  "—",
  "CONFERE (definição fenomenológica razoável de desvio da força newtoniana via fatores Q, Q̃)", False),
 ("C21", r"Q(r)\propto \left(\frac{r}{r_V}\right)^{3/2} \quad (r\ll r_V).", "C20.27",
  "CONFERE SOB HIPÓTESE (consistente com o expoente de screening de C20.27; herda a pendência de C20.09 — coeficientes Z,c3,αV postulados, não derivados dos β_n reais)", False),
 ("C21", r"g_{\mu\nu} = \eta_{\mu\nu} +\frac{1}{M_{\rm Pl}}\Big(h^{(0)}_{\mu\nu} + \kappa\,h^{(m)}_{\mu\nu}\Big) +\frac{\kappa_\pi}{M_{\rm Pl}}\pi\,\eta_{\mu\nu} +\cdots",
  "—",
  "CONFERE SOB HIPÓTESE (decomposição esquemática, declarada como tal pelo próprio texto; forma padrão de limite de desacoplamento, mas κ,κ_π não são calculados a partir da estrutura HR real da TDCP-F1 — mesma pendência de C20.09)", False),
 ("C21", r"\frac{F_\pi}{F_N} \equiv \frac{\pi'/M_{\rm Pl}}{GM/r^2} \sim \alpha_V^2\left(\frac{r}{r_V}\right)^{3/2}, \qquad (r\ll r_V).",
  "C20.27",
  "CONFERE (reprise de C20.27, com a definição explícita de F_π/F_N adicionada)", False),
 ("C21", r"\Phi(r)= -\frac{GM}{r}\left[1+\epsilon_\Phi(r)\right],\qquad \Psi(r)= -\frac{GM}{r}\left[1+\epsilon_\Psi(r)\right],",
  "C21.09",
  "CONFERE (parametrização consistente com a convenção interna do capítulo — ver nota em C21.02 sobre a troca de papéis Φ↔Ψ frente ao Cap.18/19)", False),
 ("C21", r"com \epsilon_{\Phi,\Psi}(r)\sim \mathcal{O}(F_\pi/F_N).", "C21.09/10", "CONFERE (consistente com C21.09-10)", False),
 ("C21", r"\epsilon_\Phi(r) = +c_\Phi\,\frac{F_\pi}{F_N},\qquad \epsilon_\Psi(r) = +c_\Psi\,\frac{F_\pi}{F_N},", "—",
  "INCOMPLETA — c_Φ,c_Ψ nunca são calculados a partir da mistura real dos setores g,f; permanecem números O(1) livres em todo o capítulo; a mesma pendência se propaga a C_γ=|c_Ψ-c_Φ| usado no bound de Cassini (C21.19-20)", False),
 ("C21", r"\gamma(r)\equiv\frac{\Psi}{\Phi} = \frac{1+\epsilon_\Psi(r)}{1+\epsilon_\Phi(r)} \simeq 1+\left[\epsilon_\Psi(r)-\epsilon_\Phi(r)\right] \quad (\text{em ordem linear}).",
  "C21.12",
  "CONFERE (expansão linear correta, dado εΦ,εΨ≪1: (1+εΨ)/(1+εΦ)≈(1+εΨ)(1-εΦ)≈1+εΨ-εΦ, descartando O(ε²))", False),
 ("C21", r"\gamma(r)-1 \simeq (c_\Psi-c_\Phi)\,\alpha_V^2\left(\frac{r}{r_V}\right)^{3/2}. }", "C21.09, C21.12, C21.13",
  "CONFERE (álgebra verificada: substituição direta de C21.09 e C21.12 em C21.13 reproduz esta expressão)", False),
 ("C21", r"r_V \sim \left(\frac{GM}{m^2F_0}\right)^{1/3}\left(\frac{\alpha_V c_3}{Z^2}\right)^{1/3}, \qquad F_0\equiv F(\phi_0).",
  "C20.19", "CONFERE (reprise de C20.19)", False),
 ("C21", r"\gamma(r)-1 \sim (c_\Psi-c_\Phi)\,\alpha_V^2 \left[ \frac{r^3\,m^2F_0}{GM} \left(\frac{Z^2}{\alpha_V c_3}\right) \right]^{1/2}.",
  "C21.14, C21.15",
  "CONFERE (álgebra verificada: substituindo r_V de C21.15 em (r/r_V)^{3/2} de C21.14 reproduz exatamente esta expressão)", False),
 ("C21", r"|\gamma(r)-1| \;\propto\; \alpha_V^{3/2}\, \left(\frac{Z}{\sqrt{c_3}}\right)\, \left(\frac{m\sqrt{F_0}\,r^{3/2}}{\sqrt{GM}}\right).",
  "C21.16",
  "CONFERE (álgebra verificada: expandindo a raiz de C21.16, αV²×αV^{-1/2}=αV^{3/2} e os demais fatores se separam corretamente em Z/√c3 e m√F0 r^{3/2}/√(GM))", False),
 ("C21", r"|\gamma-1| \lesssim 2.3\times 10^{-5}.", "—",
  "CONFERE (importada — valor padrão do experimento Cassini, Bertotti/Iess/Tortora 2003, γ-1=(2.1±2.3)×10⁻⁵)", False),
 ("C21", r"|\gamma(r)-1| \simeq \mathcal{C}_\gamma\, \alpha_V^2\left(\frac{r}{r_V}\right)^{3/2}, \qquad \mathcal{C}_\gamma \equiv |c_\Psi-c_\Phi|\sim \mathcal{O}(1),",
  "C21.14", "CONFERE (reprise de C21.14 com notação C_γ)", False),
 ("C21", r"r_V \gtrsim r_{\rm AU} \left(\frac{\mathcal{C}_\gamma\,\alpha_V^2}{2.3\times10^{-5}}\right)^{2/3}.", "C21.18, C21.19",
  "CONFERE (álgebra verificada: inversão correta de C21.19 usando o bound de C21.18; verificado numericamente nesta auditoria: com C_γ=α_V=1, rV≳0.006pc, satisfeito com margem de 2-3 ordens de grandeza pelo r_V^⊙~5.6-120.6pc do Cap.20)", False),
 ("C21", r"m_{\rm eff}^2 = m^2F(\phi).", "C20.04, C21.05", "CONFERE (reprise)", False),
 ("C21", r"\mathcal{L}_m[g],", "Cap.17 §17.4 (C17.14)",
  "CONFERE (reprise do acoplamento mínimo de matéria só a g, consistente com Cap.17)", False),
 ("C21", r"\left|\frac{\delta F}{F_0}\right|_{r\sim {\rm AU}} \ll 1 \quad\Rightarrow\quad \delta r_V/r_V \simeq -\frac{1}{3}\,\delta F/F_0 \ \text{desprezível}.",
  "C20.19/20 (r_V∝F0^{-1/3})",
  "CONFERE (álgebra verificada: derivada logarítmica de r_V∝F0^{-1/3} dá δr_V/r_V=-δF0/(3F0) ✓)", False),
 ("C21", r"m_\phi^2 \gg \frac{1}{{\rm AU}^2}", "C21.23",
  "INCOMPLETA — introduz uma massa própria de φ (m_φ) distinta de m_eff (C20.04), o que resolve a ambiguidade notada em C20.33, mas m_φ nunca é calculada a partir de L_φ em nenhum capítulo lido até aqui (L_φ aparece em C20.02 sem forma explícita além de F(φ))", False),
 ("C21", r"\beta_{\rm PPN}-1 \sim \mathcal{O}\!\left(\left(\frac{F_\pi}{F_N}\right)^2\right) \sim \alpha_V^4\left(\frac{r}{r_V}\right)^3,",
  "C20.27/C21.09",
  "CONFERE SOB HIPÓTESE (expectativa qualitativa padrão em teorias com screening forte — β_PPN como efeito de 2ª ordem escalando com o quadrado do fator de 1ª ordem; não é uma derivação explícita a partir da ação, apenas argumento de escala)", False),
 ("C21", r"|\beta_{\rm PPN}-1|\ll |\gamma_{\rm PPN}-1|", "C21.25",
  "CONFERE (consequência lógica de C21.25, dado r≪r_V)", False),
 ("C21", r"> \epsilon_{\Phi,\Psi}(r)\sim \alpha_V^2\left(\frac{r}{r_V}\right)^{3/2}.", "C21.09/11",
  "CONFERE (reprise, em bloco de conclusão)", False),
 ("C21", r"> \boxed{ \gamma(r)-1 \simeq \mathcal{C}_\gamma\,\alpha_V^2\left(\frac{r}{r_V}\right)^{3/2}, \qquad \mathcal{C}_\gamma\sim \mathcal{O}(1). }",
  "C21.19", "CONFERE (reprise, em bloco de conclusão)", False),
 ("C21", r"> \boxed{ r_V \sim \left(\frac{GM}{m^2F_0}\right)^{1/3}\times \mathcal{O}(1). }", "C21.15/C20.19",
  "CONFERE (reprise, em bloco de conclusão)", False),
 ("C21", r"> r_V^\odot \gg 1\,{\rm AU} \Rightarrow |\gamma-1|\ \text{é automaticamente pequeno}.", "C20.26, C21.20",
  "CONFERE (consistente com a verificação numérica desta auditoria)", False),
 ("C21", r"> \boxed{ \left|\delta F/F_0\right|_{AU}\ll 1 \quad\Rightarrow\quad \phi \text{ não reintroduz quinta força local relevante}. }",
  "C21.23, C21.24",
  "CONFERE SOB HIPÓTESE (consequência lógica de C21.23, mas a premissa |δF/F0|≪1 em si depende da dinâmica real de φ e de m_φ, nunca calculada — ver C21.24)", False),
]

def main():
    aplicados = 0
    problemas = []
    arquivos = ("C16", "C17", "C18", "C19", "C20", "C21")
    textos = {}
    for pref in arquivos:
        with open(os.path.join(REG, pref + ".md"), encoding="utf-8") as fh:
            textos[pref] = re.split(r"(?=### \[)", fh.read())
    for pref, key, dep, ver, multi in V:
        blocos = textos[pref]
        hits = [i for i, b in enumerate(blocos)
                if b.startswith("### [") and key in b and "_(pendente)_" in b]
        if not hits:
            problemas.append(f"{pref}: '{key[:60]}' -> 0 pendentes")
            continue
        if len(hits) > 1 and not multi:
            problemas.append(f"{pref}: '{key[:60]}' -> {len(hits)} blocos")
            continue
        for i in hits:
            b = blocos[i]
            b = b.replace("- **Depende de:** _(a preencher)_",
                          f"- **Depende de:** {dep}")
            b = b.replace("- **Veredito:** _(pendente)_",
                          f"- **Veredito:** {ver}")
            blocos[i] = b
            aplicados += 1
    for pref in arquivos:
        texto = "".join(textos[pref])
        with open(os.path.join(REG, pref + ".md"), "w", encoding="utf-8") as fh:
            fh.write(texto)
        print(f"{pref}: {texto.count('_(pendente)_')} pendentes")
    print(f"\naplicados: {aplicados}")
    for p in problemas:
        print("  -", p)


if __name__ == "__main__":
    main()
